name = "fqnovel-api"
# 修改这里，通常 worker-build 生成的是 index.js
main = "build/worker/index.js"
compatibility_date = "2024-09-06"

[vars]
install_id = "670078579016233"
server_device_id = "670078578733609"
aid = "1967"
update_version_code = "62532"

[build]
command = "worker-build --release"
